"""initial_schema

Revision ID: 570af04fcbf6
Revises: 
Create Date: 2026-06-18 20:34:06.528789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '570af04fcbf6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actuaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('proceso_id', sa.Integer(), nullable=False),
    sa.Column('id_reg_actuacion', sa.BigInteger(), nullable=False),
    sa.Column('cons_actuacion', sa.BigInteger(), nullable=False),
    sa.Column('fecha_actuacion', sa.String(), nullable=True),
    sa.Column('actuacion', sa.String(), nullable=True),
    sa.Column('anotacion', sa.Text(), nullable=True),
    sa.Column('fecha_inicial', sa.String(), nullable=True),
    sa.Column('fecha_final', sa.String(), nullable=True),
    sa.Column('fecha_registro', sa.String(), nullable=True),
    sa.Column('cod_regla', sa.String(), nullable=True),
    sa.Column('con_documentos', sa.Boolean(), nullable=True),
    sa.Column('cant', sa.Integer(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['proceso_id'], ['procesos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('proceso_id', 'id_reg_actuacion', name='uix_proceso_actuacion')
    )
    op.create_index(op.f('ix_actuaciones_id_reg_actuacion'), 'actuaciones', ['id_reg_actuacion'], unique=False)
    op.create_index(op.f('ix_actuaciones_proceso_id'), 'actuaciones', ['proceso_id'], unique=False)
    op.create_table('documentos_actuacion',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('actuacion_id', sa.Integer(), nullable=False),
    sa.Column('id_reg_documento', sa.BigInteger(), nullable=False),
    sa.Column('id_conexion', sa.Integer(), nullable=True),
    sa.Column('cons_actuacion', sa.BigInteger(), nullable=True),
    sa.Column('guid_documento_sxxiw', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tipo', sa.String(), nullable=True),
    sa.Column('fecha_carga', sa.String(), nullable=True),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['actuacion_id'], ['actuaciones.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('actuacion_id', 'id_reg_documento', name='uix_actuacion_documento')
    )
    op.create_index(op.f('ix_documentos_actuacion_actuacion_id'), 'documentos_actuacion', ['actuacion_id'], unique=False)
    op.create_index(op.f('ix_documentos_actuacion_id_reg_documento'), 'documentos_actuacion', ['id_reg_documento'], unique=False)
    op.add_column('procesos', sa.Column('tipo_novedad', sa.String(), nullable=True))
    op.add_column('procesos', sa.Column('categoria', sa.String(), nullable=True))
    op.add_column('procesos', sa.Column('ultima_sincronizacion', sa.DateTime(), nullable=True))
    op.add_column('procesos', sa.Column('dias_sin_cambios', sa.Integer(), nullable=True))
    op.add_column('procesos', sa.Column('fallos_consecutivos', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('username', sa.String(), nullable=True))
    op.add_column('users', sa.Column('telegram_chat_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_column('users', 'telegram_chat_id')
    op.drop_column('users', 'username')
    op.drop_column('procesos', 'fallos_consecutivos')
    op.drop_column('procesos', 'dias_sin_cambios')
    op.drop_column('procesos', 'ultima_sincronizacion')
    op.drop_column('procesos', 'categoria')
    op.drop_column('procesos', 'tipo_novedad')
    op.drop_index(op.f('ix_documentos_actuacion_id_reg_documento'), table_name='documentos_actuacion')
    op.drop_index(op.f('ix_documentos_actuacion_actuacion_id'), table_name='documentos_actuacion')
    op.drop_table('documentos_actuacion')
    op.drop_index(op.f('ix_actuaciones_proceso_id'), table_name='actuaciones')
    op.drop_index(op.f('ix_actuaciones_id_reg_actuacion'), table_name='actuaciones')
    op.drop_table('actuaciones')
    # ### end Alembic commands ###
